import Head from 'next/head'
import FirstPage from '../components/firstpage'
import Question from './question'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Quiz App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FirstPage/>
      {/* <Question /> */}
    </div>
  )
}
